id: QmSLWsdiTPxY8XtsFKQ7DEr7Qy15jMpMTUWET8YvawkNRP
description: Send message
tags: []
trigger:
    type: http
    method: POST
    paths:
        - /api/rooms/X/message
execution:
    timeout: 15s
    memory: 20MB
    call: sendMessage
source: functions/imposter/sendMessage
domains:
    - imposter_api
